### ISSUE TITLE
How we can update phonebook entries with latest release candidate ?

### ISSUE THREAD

**Issue by ronak-k-p** [DotRas/DotRas#121] opened 2024-06-03 14:25 UTC
We are planning to migrate to newer DotRas and older DotRas allows us to set following RasEntry options,
```
FramingProtocol
EntryType
ReconnectIfDropped 
DisableIKEv2Fragmentation
IPv4InterfaceMetric
IPv6InterfaceMetric
entry.Options.RemoteDefaultGateway
```

Also we were able to create new Phonebook entry by calling `RasEntry.CreateVpnEntry `

New version doesn't seem to allow updating phonebook entries or set entry options.
How can we do it using newer version ?

**Comment by jeff-winn** [comment] 2024-07-02 09:16
Right now that is intentional. Trying to get something out there, and that API has been historically the most complicated to create. My time is severely limited right now working on this, so I gotta prioritize.

Duplicate of #22

**Closed by jeff-winn** 2024-07-02 09:16 UTC
