### ISSUE TITLE
Please add RasEnumEntries support

### ISSUE THREAD

**Issue by shouhujishu** [DotRas/DotRas#107] opened 2022-03-05 09:37 UTC
private RASENTRYNAME[] GetRemoteDevices(out int count)
        {
            RASENTRYNAME[] lpRasDevInfo;
            bool retry;

            count = 1;

            do
            {
                retry = false;
                lpRasDevInfo = structFactory.CreateArray<RASENTRYNAME>(count, out var lpCb);

                var ret = api.RasEnumEntries(IntPtr.Zero,null,lpRasDevInfo, ref lpCb, ref count);
                if (ret == ERROR_BUFFER_TOO_SMALL)
                {
                    retry = true;
                }
                else if (ret != SUCCESS)
                {
                    throw exceptionPolicy.Create(ret);
                }
            } while (retry);

            return lpRasDevInfo;
        }
//----------------------------------------
 [DllImport(RasApi32Dll, CharSet = CharSet.Unicode)]
        public static extern int RasEnumEntries(
    IntPtr reserved,
    string lpszPhonebook,
    [In, Out] RASENTRYNAME[] lprasentryname,
    ref int lpcb,
    ref int lpcEntries);

**Comment by jeff-winn** [comment] 2022-08-01 02:10
Duplicate of #22

**Closed by jeff-winn** 2022-08-01 02:10 UTC
Labels: duplicate
